In [1]:
import numpy as np
import pandas as pd

In [2]:
Ro=int(input("Enter the number of rows"))
Co=int(input("Enter the number of columns"))

Mat=[]

for i in range(Ro):
    x=[]
    print("Enter the next row")
    for j in range(Co):
        x.append(int(input()))
    Mat.append(x)  
    

Enter the number of rows3
Enter the number of columns2
Enter the next row
1
5
Enter the next row
4
6
Enter the next row
5
5


In [3]:
np.array(Mat)

array([[1, 5],
       [4, 6],
       [5, 5]])

In [4]:
def Transpose(Mat,Ro,Co):
    for i in range(Co): 
        for j in range(Ro): 
            Mat_T[i][j] = Mat[j][i] 
    return Mat_T

Mat_T=np.zeros((Co,Ro))            
Mat_T=Transpose(Mat,Ro,Co)
        

In [5]:
Mat_T


array([[1., 4., 5.],
       [5., 6., 5.]])

In [6]:
def Matrix_mul(A,B):
    A_Row=len(A)
    A_Col=len(A[0])
        
    B_Row=len(B)
    B_Col=len(B[0])
    
    result=np.zeros((A_Row,B_Col))
    
    for i in range(A_Row):
        for j in range(B_Col):
            for k in range(A_Col):
                result[i][j]=result[i][j]+A[i][k]*B[k][j]
                
    return result

In [7]:
Left_Singular_Matrix=Matrix_mul(Mat,Mat_T)
Right_Singular_Matrix=Matrix_mul(Mat_T,Mat)

In [8]:
Right_Singular_Matrix

array([[42., 54.],
       [54., 86.]])

In [9]:
valuesU,vectorsU=np.linalg.eig(Left_Singular_Matrix)
valuesV,vectorsV=np.linalg.eig(Right_Singular_Matrix)


In [10]:
vectorsV

array([[-0.82984845, -0.55798885],
       [ 0.55798885, -0.82984845]])

In [11]:
valuesU

array([1.22309519e+02, 5.69048105e+00, 1.41902779e-15])

In [12]:
vectorsU

array([[-0.4256331 , -0.82168017,  0.37904902],
       [-0.65203085, -0.0119638 , -0.75809804],
       [-0.627449  ,  0.56982327,  0.53066863]])

In [13]:
import math

def GramScmdict(vectorsU):
    result11=[]
    for ele in vectorsU:
        result10=0
        for i in ele:
            result10=(result10+i*i)
        result11.append(math.sqrt(result10))

    for i in range(len(vectorsU)):
        for j in range(len(vectorsU[0])):
            vectorsU[i][j]=vectorsU[i][j]/result11[i]
    return vectorsU        
    

In [14]:
vectorsU=GramScmdict(vectorsU)
vectorsV=GramScmdict(vectorsV)

In [15]:
vectorsV

array([[-0.82984845, -0.55798885],
       [ 0.55798885, -0.82984845]])

In [16]:
vectorsU

array([[-0.4256331 , -0.82168017,  0.37904902],
       [-0.65203085, -0.0119638 , -0.75809804],
       [-0.627449  ,  0.56982327,  0.53066863]])

In [17]:
valuesU

array([1.22309519e+02, 5.69048105e+00, 1.41902779e-15])

In [18]:
sigma_matrix=np.zeros((Ro,Ro))

In [19]:
for i in range(len(sigma_matrix)):
    for j in range(len(sigma_matrix[0])):
        if (i==j):
            sigma_matrix[i][j]=int(math.sqrt(valuesU[i]))

In [20]:
print("After SVD decomposition,the value of U will be {},the value of V will be {} and the value of sigma will be{}".format(vectorsU,vectorsV,sigma_matrix))

After SVD decomposition,the value of U will be [[-0.4256331  -0.82168017  0.37904902]
 [-0.65203085 -0.0119638  -0.75809804]
 [-0.627449    0.56982327  0.53066863]],the value of V will be [[-0.82984845 -0.55798885]
 [ 0.55798885 -0.82984845]] and the value of sigma will be[[11.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  0.]]


In [21]:
print(sigma_matrix)

[[11.  0.  0.]
 [ 0.  2.  0.]
 [ 0.  0.  0.]]
